/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColegioVistas;

import ColegioClases.Alumno;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Barbara
 */
public class FormularioAlumno extends javax.swing.JInternalFrame {

    private HashSet<Alumno> alumnos;

    /**
     * Creates new form FormularioAlumno
     */
    public FormularioAlumno(HashSet<Alumno> alumnos) {
        initComponents();
        this.alumnos = alumnos;
        this.getContentPane().setSize(300, 500);
        this.getContentPane().setBackground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormulariodeAlumnos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLEGAJO = new javax.swing.JLabel();
        jtLegajo = new javax.swing.JTextField();
        jAPELLIDO = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jNOMBRE = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jGUARDAR = new javax.swing.JButton();
        jNUEVO = new javax.swing.JButton();
        jSALIR = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(450, 300));

        jFormulariodeAlumnos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFormulariodeAlumnos.setText("Formulario de Alumnos");

        jLEGAJO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLEGAJO.setText("LEGAJO:");

        jAPELLIDO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jAPELLIDO.setText("APELLIDO:");

        jNOMBRE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNOMBRE.setText("NOMBRE:");

        jGUARDAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGUARDAR.setText("GUARDAR");
        jGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGUARDARActionPerformed(evt);
            }
        });

        jNUEVO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jNUEVO.setText("NUEVO");
        jNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNUEVOActionPerformed(evt);
            }
        });

        jSALIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSALIR.setText("SALIR");
        jSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormulariodeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEGAJO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jGUARDAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSALIR)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFormulariodeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEGAJO)
                    .addComponent(jtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAPELLIDO)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNOMBRE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGUARDAR)
                    .addComponent(jNUEVO)
                    .addComponent(jSALIR))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSALIRActionPerformed

    private void jNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNUEVOActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jNUEVOActionPerformed

    private void jGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGUARDARActionPerformed

        int legajo = Integer.parseInt(jtLegajo.getText());
        String apellido = jtApellido.getText();
        String nombre = jtNombre.getText();

        Alumno alumnoNvo = new Alumno(legajo, apellido, nombre);
        alumnos.add(alumnoNvo);
        JOptionPane.showMessageDialog(this, "Alumno cargado exitosamente");
    }//GEN-LAST:event_jGUARDARActionPerformed

    private void limpiar() {

        jtLegajo.setText("");
        jtApellido.setText("");
        jtNombre.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAPELLIDO;
    private javax.swing.JLabel jFormulariodeAlumnos;
    private javax.swing.JButton jGUARDAR;
    private javax.swing.JLabel jLEGAJO;
    private javax.swing.JLabel jNOMBRE;
    private javax.swing.JButton jNUEVO;
    private javax.swing.JButton jSALIR;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtLegajo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
