/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColegioVistas;

import ColegioClases.Alumno;
import ColegioClases.Materia;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Barbara
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

    private HashSet<Alumno> alumnos;
    private HashSet<Materia> materias;

    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion(HashSet<Alumno> alumnos, HashSet<Materia> materias) {
        initComponents();
        this.alumnos = alumnos;
        this.materias = materias;
        agregarAlumno();
        agregarMateria();
        this.getContentPane().setBackground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFORMULARIOdeINSCRIPCION = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jELEGIRMATERIA = new javax.swing.JLabel();
        jComboMateria = new javax.swing.JComboBox<>();
        jELEGIRALUMNO = new javax.swing.JLabel();
        jComboAlumno = new javax.swing.JComboBox<>();
        jINSCRIBIR = new javax.swing.JButton();
        jSALIR = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(450, 300));

        jFORMULARIOdeINSCRIPCION.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFORMULARIOdeINSCRIPCION.setText("Formulario de Inscripcion");

        jELEGIRMATERIA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jELEGIRMATERIA.setText("ELIJA UNA MATERIA:");

        jComboMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMateriaActionPerformed(evt);
            }
        });

        jELEGIRALUMNO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jELEGIRALUMNO.setText("ELIJA UN ALUMNO:");

        jINSCRIBIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jINSCRIBIR.setText("INSCRIBIR");
        jINSCRIBIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jINSCRIBIRActionPerformed(evt);
            }
        });

        jSALIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSALIR.setText("SALIR");
        jSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jELEGIRMATERIA)
                                    .addComponent(jELEGIRALUMNO))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 68, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jINSCRIBIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSALIR)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jFORMULARIOdeINSCRIPCION)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jFORMULARIOdeINSCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jELEGIRMATERIA)
                    .addComponent(jComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jELEGIRALUMNO)
                    .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jINSCRIBIR)
                    .addComponent(jSALIR))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSALIRActionPerformed

    private void jComboMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMateriaActionPerformed

    private void jINSCRIBIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jINSCRIBIRActionPerformed
        // TODO add your handling code here:
        Alumno seleccionado = (Alumno) jComboAlumno.getSelectedItem();

        Materia seleccionada = (Materia) jComboMateria.getSelectedItem();
        seleccionado.agregarMateria(seleccionada);

        JOptionPane.showMessageDialog(null, "Inscripción de alumno exitosa");


    }//GEN-LAST:event_jINSCRIBIRActionPerformed
    private void agregarAlumno() {
        for (Alumno a1 : alumnos) {

            jComboAlumno.addItem(a1);

        }

    }

    private void agregarMateria() {
        for (Materia m1 : materias) {

            jComboMateria.addItem(m1);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> jComboAlumno;
    private javax.swing.JComboBox<Materia> jComboMateria;
    private javax.swing.JLabel jELEGIRALUMNO;
    private javax.swing.JLabel jELEGIRMATERIA;
    private javax.swing.JLabel jFORMULARIOdeINSCRIPCION;
    private javax.swing.JButton jINSCRIBIR;
    private javax.swing.JButton jSALIR;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
